package steps.api;

import net.thucydides.core.annotations.Step;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;

import static net.serenitybdd.rest.SerenityRest.given;

public class EarlyAccessProductFeedControllerAPISteps {

    @Step
    public void earlyAccessFileUpload() throws IOException {
        String earlyAccessURL = "http://earlyaccess.cluboautomation.test.ostk.com:8080";

        Random rand = new Random();
        int productId = rand.nextInt(10000);

        boolean productsFile = false;
        File file;
        try {
            file = new File("EarlyAccessProducts.txt");
            file.createNewFile();

            BufferedWriter writer = new BufferedWriter(new FileWriter(file.getName()));
            writer.write("" + Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.write("\n"+Math.abs(rand.nextInt()));
            writer.close();
            System.out.println(file.getAbsolutePath());

            given().multiPart("file", file, "application/txt")
                    .when()
                    .post(earlyAccessURL + "/early/access/product/feed/file/upload")
                    .then().statusCode(200);

        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    @Step
    public void earlyAccessFileUploadUpdate() throws IOException {
        String earlyAccessURL = "http://earlyaccess.cluboautomation.test.ostk.com:8080";

        Random rand = new Random();
        int productId = rand.nextInt(10000);

        boolean productsFile = false;
        File file;
        try {
            file = new File("EarlyAccessProductsUpdate.txt");
            file.createNewFile();

            BufferedWriter writer = new BufferedWriter(new FileWriter(file.getName()));
            writer.write(Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.write("\n"+Math.abs(rand.nextInt())+ ",I,9/15/2019");
            writer.close();
            System.out.println(file.getAbsolutePath());
            given().multiPart("file", file, "application/txt")
                    .when()
                    .put(earlyAccessURL + "/early/access/product/feed/file/upload/update")
                    .then().statusCode(200);

        } catch (IOException e) {
            e.printStackTrace();
        }

    }


}